package com.projectgps.demo.gpsdata;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.io.Serializable;
import java.util.Comparator;
import java.util.Date;
/**
 * @author adhameldda
 */

@DynamoDBTable(tableName = "LocationRequest")
public class LocationRequest implements Serializable, Comparable<LocationRequest>{


    private String id;
    private String userId;
    private float latitude;
    private float longitude;
    private long time;


    public LocationRequest(String id, String userId, float latitude, float longitude, long time) {
        this.id = id;
        this.userId = userId;
        this.latitude = latitude;
        this.longitude = longitude;
        this.time = time;
    }
    public LocationRequest(String userId, float latitude, float longitude, long time) {
        this.userId = userId;
        this.latitude = latitude;
        this.longitude = longitude;
        this.time = time;
    }
      public LocationRequest(){}
    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    @DynamoDBRangeKey
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
    @DynamoDBAttribute
    public float getLatitude() {
        return latitude;
    }

    public void setLatitude(float latitude) {
        this.latitude = latitude;
    }
    @DynamoDBAttribute
    public float getLongitude() {
        return longitude;
    }

    public void setLongitude(float longitude) {
        this.longitude = longitude;
    }
    @DynamoDBAttribute
    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    @Override
    public String toString() {
        return "LocationRequest{" +
                "id=" + id +
                ", userId=" + userId +
                ", latitude=" + latitude +
                ", longitude=" + longitude +
                ", time=" + time +
                '}';
    }




    public int compareTo(LocationRequest o) {
        return this.getTime()<o.getTime()?-1:
                this.getTime()>o.getTime()?1:0;
    }
}
