package com.projectgps.demo.gpsdata;
/**
 *
 * @author Eldda adham
 */
import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Settings")
public class Settings {

    private String id;
    private String name;
    private String value;

    public Settings(String id, String name, String value) {
        this.id = id;
        this.name = name;
        this.value = value;
    }
    public Settings(String name, String value) {
        this.name = name;
        this.value = value;
    }
    public Settings(){}


    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    @DynamoDBRangeKey
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    @DynamoDBAttribute
    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return "Settings{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", value='" + value + '\'' +
                '}';
    }
}
