package com.projectgps.demo.gpsdata;
/**
 *
 * @author Eldda adham
 */
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Date;

@DynamoDBTable(tableName = "User")
public class User {



    private String id ;
    private String fullName;
    private String userName;
    private String password;
    @JsonProperty
    private boolean isActive;
    private long joinedAt;


    public User(String userName, String password) {
        this.userName = userName;
        this.password = password;
    }

    public User(String id, String fullName, String userName, boolean isActive, long joinedAt) {
        this.id = id;
        this.fullName = fullName;
        this.userName = userName;
        this.isActive = isActive;
        this.joinedAt = joinedAt;
    }
    public User(String fullName, String userName, boolean isActive, long joinedAt) {
        this.fullName = fullName;
        this.userName = userName;
        this.isActive = isActive;
        this.joinedAt = joinedAt;
    }
    public User(){}

   @DynamoDBHashKey(attributeName="id")
   @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    @DynamoDBAttribute
    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    @DynamoDBRangeKey
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
    @DynamoDBAttribute
    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }
    @DynamoDBAttribute
    public long getJoinedAt() {
        return joinedAt;
    }

    public void setJoinedAt(long joinedAt) {
        this.joinedAt = joinedAt;
    }
    @DynamoDBAttribute
    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", fullName='" + fullName + '\'' +
                ", userName='" + userName + '\'' +
                ", Password='" + password + '\'' +
                ", isActive=" + isActive +
                ", joinedAt=" + joinedAt +
                '}';
    }


}



